codecov:
    bot: "umpire"

coverage:
    round: up
    precision: 2
    status:
        patch: off
        project:
            default: false
            pavilion:
                target: 80%
                paths: 
                    - pavilion/
