version: "3.8"

services:
  pitch:
    networks:
      - oval
    build: 
      context: ./pitch/
      dockerfile: Dockerfile
    ports:
      - "19000-19010:19000-19010"
    command: >
      sh -c "yarn &&
             yarn start"
    env_file: .env
    volumes:
      - ${PWD}/pitch/:/home/pitch/

  app:
    networks:
      - oval
      - long-room
    build:
      context: ./Server
    user: root
    ports:
      - "8000:8000"
    volumes:
      - ./Server/app:/app
    command:  >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py setup &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - InsecureTransportError=1
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword  
    networks:
        - long-room

networks:
  oval:
  
  long-room:
