version: "3.8"

services:
  pitch:
    build: 
      context: ./pitch/
      dockerfile: Dockerfile
    ports:
      - "19000-19010:19000-19010"
    command: >
      sh -c "yarn &&
             yarn start"
    env_file: .env
    volumes:
      - ${PWD}/pitch/:/home/pitch/

