version: "3.8"

services:
  pitch:
    networks:
      - host
    build: 
      context: ./pitch/
      dockerfile: Dockerfile
      network: host
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    env_file: .env
    volumes:
      - ${PWD}/pitch/:/home/pitch/


networks:
  host:
    external: true
