version: "3.8"

services:
  pitch:
    container_name: pitch
    networks:
      - host
    build: 
      context: ./App/
      dockerfile: Dockerfile
      network: host
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    env_file: .env
    volumes:
      - ${PWD}/App/:/home/App/


networks:
  host:
    external: true
