name: Django Server Tests

on:
  pull_request:
    branches:
      - master
jobs:
  core-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Core App Tests
        working-directory: ./Server
        run: docker-compose run app sh -c "python manage.py test core"
  user-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: User App Tests
        working-directory: ./Server
        run: docker-compose run app sh -c "python manage.py test user"

